name: ProtectionStones
version: ${version}
description: ${description}
authors: [Vik1395,Dragoboss,Jarzean,Dylan-BukkitPlugins]

depend: [WorldGuard, WorldEdit]
main: me.vik1395.ProtectionStones.ProtectionStones
api-version: 1.13

commands:
  ps:
    description: Teleports player to a random position within the world border.
    aliases: [protectionstone, protectionstones, pstone]
    usage: /ps help